### ISSUE TITLE
Remove current Imgur upload functionality

### ISSUE THREAD

**Issue by Tursko** [shotr-io/shotr-3#100]
Let's remove this since it's account-less and users can't manage the data they upload.

**Comment by zacbre** [comment]
We should really remove it, and re-add it through a new module for managing "custom uploaders" but have a template for popular ones.

**Comment by zacbre** [comment]
I'm actually going to move this to a new ticket that describes the refactor process.

**Comment by zacbre** [comment]
https://github.com/shotr-io/shotr-3/issues/130
