### ISSUE TITLE
Virtual Audio Capturer causing PUA/ShotrAudioSniffer with Windows Defender

### ISSUE THREAD

**Issue by zacbre** [shotr-io/shotr-3#118]
Virtual Audio Capturer DShow plugin for ffmpeg is causing a potentially unwanted application warning with defender...rename to something a little less bad than "audio sniffer"

Suggested: ffmpeg-dshow-audio

**Comment by Tursko** [comment]
Here is the false positive report from Windows. 

https://www.microsoft.com/en-us/windows/comprehensive-security?ocid=cx-wdsi-ency

Certainly that module was ready for a name change lol, can't blame them.
