### ISSUE TITLE
Cannot resize screenshot below certain height

### ISSUE THREAD

**Issue by CoderTypist** [shotr-io/shotr-3#124]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature/enhancement request or a discussion topic

----------------------------------------

### Bug description
A screenshot, once taken, cannot be resized below a certain height.

### Steps to reproduce the bug
- Take a screenshot.
- Try to resize the image such that it has no height.

**Actual result:** You cannot reduce the height below a certain point.
**Expected result:** Screenshot height should be allowed to be smaller.

### Version info
**Shotr Version:** 3.1.5

**Comment by Tursko** [comment]
The 'certain height' is currently 50. I will reduce it down to 1.

**Comment by zacbre** [comment]
closed with #126
