### ISSUE TITLE
Editing hotkeys still allows screen capture + override

### ISSUE THREAD

**Issue by Tursko** [shotr-io/shotr-3#15]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature/enhancement request or a discussion topic

----------------------------------------

### Bug description
When changing a hotkey, you can still use another hotkey to take a screenshot.

### Steps to reproduce the bug
- Edit a hotkey
- Make the hotkey something that's already set.

**Actual result:** Shotr is still listening for hotkeys and will take a screenshot

**Expected result:** All hotkeys should be disabled and be able to be overritten.

### Version info

**Shotr Version:** v.1.1.8.1 +

**Comment by ThrDev** [comment]
Can we get more context on this? I will look into this once I know how to reproduce.

**Comment by Tursko** [comment]
Yes. 

Just try to set one of the hotkeys to something that's already set.

The fix would he to disable any screen capture or upload function while changing hotkeys. Also hot keys should be able to over ride each other. If I want my hot key to be something that's already set, then it should simply remove it from the other.

**Comment by Tursko** [comment]
Any hotkey should be able to override another hotkey. This means ALL hotkeys should be disabled when editting any hotkey.

**Comment by Tursko** [comment]
Related https://github.com/shotr-io/shotr-3/issues/35
