### ISSUE TITLE
Test Installer on Several DPI Changes

### ISSUE THREAD

**Issue by ThrDev** [shotr-io/shotr-3#29]
We need to test the installer on different DPI settings, i.e:
```
100%
125%
150%
200%
```

**Comment by Tursko** [comment]
I can do this today.

**Comment by Tursko** [comment]
|                |1080P                          |1440P                         |
|----------------|-------------------------------|-----------------------------|
|100%			|`PASS`          				|`PASS`            |
|125%          |`PASS`           				|`PASS`             |
|150%          |`PASS`							|`PASS`  |
|175%			|`PASS`          				|`PASS`             |
|200%          |`NA`            				|`PASS`           |
|225%          |`NA`							|`PASS`  |
