### ISSUE TITLE
Add "Open Containing Folder" button to locally saved images if save to directory is enabled

### ISSUE THREAD

**Issue by ThrDev** [shotr-io/shotr-3#54]
On windows notifications

**Comment by Tursko** [comment]
You should be able to do this with the right click sub menu. Right click "open containing folder"

**Comment by ThrDev** [comment]
This is more meant for notifications, but yes we can do that too.

**Comment by ThrDev** [comment]
Actually, negative. We cannot do that, as we don't link a local image with a remote one.
