### ISSUE TITLE
Reduce list of colors in 'E' Edit mode

### ISSUE THREAD

**Issue by Tursko** [shotr-io/shotr-3#66]
Reduce to common colors. Remove transparent color.

https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.colors?view=net-5.0

https://github.com/shotr-io/shotr-3/blob/78615fcf29e8f2afab18b1d9588f18bf8e4d7b26/src/Shotr.Ui/Forms/ScreenshotForm.cs#L89

I don't see an elegant way to do this other than just hard coding x amount of values (probably the common primary colors). 

**C# Colors:**
1. Color.Black
2. Color.White
3. Color.Red
4. Color.Orange
5. Color.Yellow
6. Color.Green
7. Color.Blue
8. Color.Indigo
9. Color.Violet

**Comment by Tursko** [comment]
https://docs.microsoft.com/en-us/dotnet/api/system.windows.media.colors?view=net-5.0

**Comment by ThrDev** [comment]
This can be done by just using the Color enum:
```cs
Color.Red
Color.White
Color.Blue
// etc..
```
