### ISSUE TITLE
Fix Color Picker Font Size / Measurement

### ISSUE THREAD

**Issue by ThrDev** [shotr-io/shotr-3#69]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature/enhancement request or a discussion topic

----------------------------------------

### Bug description
The color picker font is small again at anything greater than 100% dpi scaling.

### Steps to reproduce the bug
Ctrl+Shift+C

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behavior)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behavior)

### Screenshots
![image](https://user-images.githubusercontent.com/5459179/107109517-2c2ee100-680f-11eb-8252-d070c13eaa44.png)

### Version info
**Shotr Version:** 3.0.9

**Comment by Tursko** [comment]
![image](https://user-images.githubusercontent.com/18274896/107110096-c7718780-680a-11eb-87b3-a8ad119518d0.png)
