### ISSUE TITLE
Default hotkeys changed

### ISSUE THREAD

**Issue by Tursko** [shotr-io/shotr-3#72]
Set new hotkey defaults. They seem to be changed. 

Default in 3.0.9
![image](https://user-images.githubusercontent.com/18274896/107111125-fd1a6e80-6812-11eb-87d2-d66a3cbce012.png)

What is should be:
Ctrl + Shift + ~
Ctrl + Shift + 1
Ctrl + Shift + 2
Ctrl + Shift + 3
Ctrl + Shift + 4
Ctrl + Shift + C

**Comment by ThrDev** [comment]
Do we want to force this on everyone or only new users? If we force this we will need to let people know that the hotkeys changed, otherwise people may get confused.

**Comment by Tursko** [comment]
> Do we want to force this on everyone or only new users? If we force this we will need to let people know that the hotkeys changed, otherwise people may get confused.

Yes, people were already confused why after this update the region capture changed to Ctrl + Shift + 4. 

So I'm just setting this back to what it originally defaulted to. They can still change it of course.

**Comment by ThrDev** [comment]
> > Do we want to force this on everyone or only new users? If we force this we will need to let people know that the hotkeys changed, otherwise people may get confused.
> 
> Yes, people were already confused why after this update the region capture changed to Ctrl + Shift + 4.
> 
> So I'm just setting this back to what it originally defaulted to. They can still change it of course.

Let's get a notification set up for non-new users that deals with this upon launch, and has a don't show again notification.

**Comment by Tursko** [comment]
> > > Do we want to force this on everyone or only new users? If we force this we will need to let people know that the hotkeys changed, otherwise people may get confused.
> > 
> > 
> > Yes, people were already confused why after this update the region capture changed to Ctrl + Shift + 4.
> > So I'm just setting this back to what it originally defaulted to. They can still change it of course.
> 
> Let's get a notification set up for non-new users that deals with this upon launch, and has a don't show again button.

The 'reset default hotkeys' already sorta does this though right? The functionality isn't there currently, but all they would have to do is click that button.
