### ISSUE TITLE
"Save as type" .png does not display other .png files in directory

### ISSUE THREAD

**Issue by CoderTypist** [shotr-io/shotr-3#76]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature/enhancement request or a discussion topic

----------------------------------------

### Bug description
Cannot see other .png files in a directory when using "Save to File" after taking a screenshot. 

### Steps to reproduce the bug
- Take a screenshot
- Select "Save to File"
- Other file types will not be displayed

**Actual result:** Other .png files in the directory are not visible

![image](https://user-images.githubusercontent.com/39784989/107139159-aed2a180-68de-11eb-9d35-5104438e1ab3.png)

**Expected result:** Other .png files in the directory should be visible

![image](https://user-images.githubusercontent.com/39784989/107139170-cf026080-68de-11eb-9649-ff961dee1cb1.png)

### Screenshots
I am not sure if this has to do with the issue. Whenever I use the snipping tool to take a screenshot, I get this:

![image](https://user-images.githubusercontent.com/39784989/107139049-e9880a00-68dd-11eb-8afd-a4c5466c9b72.png)

But Shotr shows me this:

![image](https://user-images.githubusercontent.com/39784989/107139083-12100400-68de-11eb-9d06-98a8e2bf24e3.png)

Admittedly, I do not know why my computer is saving .png files as .PNG. This personally bothers me and I have been manually renaming my files to end with ".png"

### Version info

**Shotr Version:** 3.0.9

**Comment by Tursko** [comment]
This is how I see it when I save something in paint. 
![image](https://user-images.githubusercontent.com/18274896/107139236-4a641200-68df-11eb-9168-c1c9d84b883f.png)

I'll take a look at this. Thanks for the report.
