### ISSUE TITLE
Shotr not launching during startup

### ISSUE THREAD

**Issue by Tursko** [shotr-io/shotr-3#80]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature/enhancement request or a discussion topic

----------------------------------------

### Bug description
Shotr isn't launching on startup. 

### Steps to reproduce the bug
- Complete fresh install (nothing in %APPDATA%)
- Turn on the startup setting

**Actual result:** Doesn't start with Windows

**Expected result:** Should start

### Version info

**Shotr Version:** 3.0.9

**Comment by ThrDev** [comment]
This has to do with the installer not creating the registry keys.
If you want to force it, uncheck startup and re-check startup in the client and it should work then.

We should fix this in 3.1.

**Comment by Tursko** [comment]
> This has to do with the installer not creating the registry keys.
> If you want to force it, uncheck startup and re-check startup in the client and it should work then.
> 
> We should fix this in 3.1.

I can confirm this. Works fine after turning it on and off.
