### ISSUE TITLE
History tab shows uploads with UTC, not localized timezone.

### ISSUE THREAD

**Issue by ThrDev** [shotr-io/shotr-3#82]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature/enhancement request or a discussion topic

----------------------------------------

### Bug description
The uploads in the history tab are shown with UTC time, not localized time.

**Expected result:** 
Results should be shown with your own timezone.

### Version info

**Shotr Version:** 3.0.9

**Comment by Tursko** [comment]
DateTime.ToLocalTime()
