### ISSUE TITLE
View Account button does nothing

### ISSUE THREAD

**Issue by Tursko** [shotr-io/shotr-3#97]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature/enhancement request or a discussion topic

----------------------------------------

### Bug description
Describe here the issue that you are experiencing.

### Steps to reproduce the bug
- Click view account button
- list the steps
- that reproduce the bug

**Actual result:** nothing

**Expected result:** Should open shotr gallery in browser

### Version info

**Shotr Version:** 3.0.9

**Comment by ThrDev** [comment]
This will need to contact the API to generate a one-time key that then can be used to get into Shotr with your account.
