### ISSUE TITLE
Unhandled exception after login

### ISSUE THREAD

**Issue by Tursko** [shotr-io/shotr-3#98]
- [x] I have searched open and closed issues for duplicates
- [x] I am submitting a bug report for existing functionality that does not work as intended
- [x] This isn't a feature/enhancement request or a discussion topic

----------------------------------------

### Bug description
I'll describe later 

### Steps to reproduce the bug
- using hyphens as bullet points
- list the steps
- that reproduce the bug

**Actual result:** Describe here what happens after you run the steps above (i.e. the buggy behavior)

**Expected result:** Describe here what should happen after you run the steps above (i.e. what would be the correct behavior)

### Version info

**Shotr Version:** 3.0.9

**Comment by thrdev** [comment]
@Tursko any more details on this one?

**Comment by Tursko** [comment]
Only happens on a fresh install. Just try to login, it will log you in but throw an exception.

**Comment by thrdev** [comment]
Saving this here for later: 
![image](https://user-images.githubusercontent.com/5459179/121535704-6502e080-c9d0-11eb-8609-47aed1cd1e3d.png)
