### ISSUE TITLE
Custom Uploader Support

### ISSUE THREAD

**Issue by LloydLabs** [shotr-io/shotr-3#99]
## 📝 Provide a description of the new feature

It'd be great if Shotr supported ShareX out of the box, as an alternative client to the core uploader. Although, this would have to mean the client <-> server protocol was easily implementable in the constraints of ShareX,

---

If you'd like to see this feature implemented, add a 👍 reaction to this post.

**Comment by Tursko** [comment]
Does ShareX host images via their own servers? Or are you talking about the idea of custom uploaders in general?

**Comment by LloydLabs** [comment]
A custom uploader, in general :)

**Comment by Tursko** [comment]
> A custom uploader, in general :)

Previous versions of Shotr did have custom uploader support. I'm actually unsure if 3.x has it since we've been focused on other enhancements. 

Since this is something we previously had, I'm sure we will re-implement it soon. I'd also like to remove the account less Imgur uploads.

**Comment by ThrDev** [comment]
Hey @LloydLabs,

I think we'll target this for the ~3.2 release.

**Comment by zacbre** [comment]
https://github.com/shotr-io/shotr-3/issues/130
